# Generated by Django 5.2.17 on 2026-09-22 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('ressource', models.CharField(max_length=100)),
                ('identifiant_ressource', models.CharField(blank=True, max_length=100)),
                ('resultat', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='SUCCES', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux_audit', to='organizations.organisation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_action',),
                'indexes': [models.Index(fields=['organisation', '-date_action'], name='audit_journ_organis_7bab3d_idx'), models.Index(fields=['utilisateur', '-date_action'], name='audit_journ_utilisa_486ba0_idx'), models.Index(fields=['ressource', 'identifiant_ressource'], name='audit_journ_ressour_13a420_idx')],
            },
        ),
    ]
