"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url
import psycopg


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",

    "accounts",
    "organizations",
    "energy",
    "analysis",
    "billing",
    "audit",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



def postgres_est_disponible():
    """
    Vérifie si PostgreSQL est accessible.
    Cette vérification est utilisée uniquement en développement.
    """
    try:
        with psycopg.connect(
            dbname=os.getenv("POSTGRES_DB", "ecoscan"),
            user=os.getenv("POSTGRES_USER", "ecoscan"),
            password=os.getenv("POSTGRES_PASSWORD", ""),
            host=os.getenv("POSTGRES_HOST", "localhost"),
            port=os.getenv("POSTGRES_PORT", "5432"),
            connect_timeout=2,
        ):
            return True

    except psycopg.Error:
        return False


if DEBUG:
    choix_db_local = os.getenv(
        "DB_BACKEND",
        "postgresql",
    ).lower()

    fallback_sqlite = os.getenv(
        "DB_ALLOW_SQLITE_FALLBACK",
        "True",
    ).lower() == "true"

    configuration_postgresql = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "ecoscan"),
        "USER": os.getenv("POSTGRES_USER", "ecoscan"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }

    configuration_sqlite = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

    if choix_db_local == "sqlite":
        DATABASES = {
            "default": configuration_sqlite,
        }

        print(
            "[BASE DE DONNÉES] "
            "SQLite est utilisé volontairement."
        )

    elif fallback_sqlite and not postgres_est_disponible():
        DATABASES = {
            "default": configuration_sqlite,
        }

        print(
            "[AVERTISSEMENT] PostgreSQL est indisponible."
        )
        print(
            "[BASE DE DONNÉES] "
            "Bascule automatique vers SQLite."
        )

    else:
        DATABASES = {
            "default": configuration_postgresql,
        }

        print(
            "[BASE DE DONNÉES] "
            "PostgreSQL local est utilisé."
        )

else:
    DATABASE_URL = os.getenv("DATABASE_URL")

    if not DATABASE_URL:
        raise ValueError(
            "DATABASE_URL doit être définie en production."
        )

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }

    print(
        "[BASE DE DONNÉES] "
        "PostgreSQL Supabase est utilisé."
    )



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
         'OPTIONS': {
            'min_length': 8, 
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_PASSWORD_VALIDATORS = []
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Dakar"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.Utilisateur"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "ORDERING_PARAM": "ordering",
    
    # Activation et limitation du nombre de requêtes (Rate Limiting)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # Pour les utilisateurs non connectés (Onboarding, Login)
        "rest_framework.throttling.UserRateThrottle",  # Pour les utilisateurs connectés
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",  # Max 10 requêtes par minute pour un anonyme / une IP
        "user": "100/minute", # Max 100 requêtes par minute pour un membre connecté
        "invitation_validation": "5/minute", # Limitation spécifique pour les tentatives d'activation
    }
}

# --- Configuration de l'expiration des tokens de sécurité ---
# Durée de validité du lien d'invitation/activation (default_token_generator)
PASSWORD_RESET_TIMEOUT = 172800  # 48 heures exprimées en secondes (48 * 3600)

# --- Configuration des durées des jetons de Session (JWT) ---
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),   # Session active de 15 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),     # Possibilité de rester connecté 7 jours
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_REVOKED_TOKENS": True,
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
