# Generated by Django 5.2.17 on 2026-09-17 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('SOMBRE', 'Sombre'), ('CLAIR', 'Clair')], default='SOMBRE', max_length=10)),
                ('densite', models.CharField(choices=[('COMPACTE', 'Compacte'), ('CONFORTABLE', 'Confortable'), ('AEREE', 'Aérée')], default='CONFORTABLE', max_length=15)),
                ('accent', models.CharField(choices=[('GREEN', 'Émeraude Solaire'), ('CYAN', 'Cyan Électrique'), ('AMBER', 'Ambre Vigilance')], default='GREEN', max_length=10)),
                ('alertes_email', models.BooleanField(default=True)),
                ('briefing_quotidien', models.BooleanField(default=True)),
                ('detection_anomalies', models.BooleanField(default=True)),
                ('rapport_hebdomadaire', models.BooleanField(default=False)),
                ('delai_inactivite_minutes', models.PositiveIntegerField(default=30)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
