# Generated by Django 5.2.17 on 2026-09-12 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('perimetre_analyse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('secteur', models.CharField(max_length=120)),
                ('localisation', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('ARCHIVEE', 'Archivée')], default='EN_ATTENTE', max_length=20)),
                ('defaut_paiement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(max_length=50)),
                ('fiche_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='organizations.ficheprojet')),
            ],
        ),
        migrations.AddField(
            model_name='ficheprojet',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_projet', to='organizations.organisation'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('fuseau_horaire', models.CharField(max_length=80)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('type_energie', models.CharField(max_length=80)),
                ('unite', models.CharField(max_length=30)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('statut_synchronisation', models.CharField(max_length=50)),
                ('derniere_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('activites', models.ManyToManyField(blank=True, related_name='compteurs', to='organizations.activite')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='organizations.site')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_affiliation', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organizations.organisation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations_membres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'utilisateur'), name='utilisateur_organisation_unique')],
            },
        ),
    ]
