# Generated by Django 5.2.17 on 2026-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_configurationsecurite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='type_compte',
            field=models.CharField(choices=[('SIMPLIFIE', 'Simplifié'), ('COMPLET', 'Complet')], default='COMPLET', max_length=12),
        ),
    ]
