# Generated by Django 5.2.17 on 2026-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organisation_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='puissance_souscrite_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance souscrite contractuelle (kVA), telle que déclarée sur la facture ou le contrat Senelec.', max_digits=8, null=True),
        ),
    ]
