# Generated by Django 5.2.17 on 2026-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='details_demande',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
