# Generated by Django 5.2.17 on 2026-10-08 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organisation_details_demande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='organizations.site')),
            ],
            options={
                'ordering': ('site__nom', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('categorie', models.CharField(max_length=100)),
                ('puissance_nominale_kw', models.DecimalField(decimal_places=3, max_digits=12)),
                ('puissance_veille_kw', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('etat_operationnel', models.CharField(choices=[('ON', 'En marche'), ('OFF', "À l'arrêt"), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10)),
                ('criticite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=12)),
                ('monitoring_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='organizations.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='energy_assets.zone')),
            ],
            options={
                'ordering': ('site__nom', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('SIMULATED', 'Simulé'), ('REAL', 'Réel')], default='SIMULATED', max_length=12)),
                ('frequence_secondes', models.PositiveIntegerField(default=15)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif')], default='ACTIVE', max_length=10)),
                ('derniere_communication', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='energy_assets.equipement')),
            ],
            options={
                'ordering': ('identifiant',),
                'indexes': [models.Index(fields=['statut', 'derniere_communication'], name='capteur_statut_last_idx')],
            },
        ),
        migrations.CreateModel(
            name='EtatEquipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etat_souhaite', models.CharField(choices=[('ON', 'En marche'), ('OFF', "À l'arrêt"), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10)),
                ('etat_rapporte', models.CharField(choices=[('ON', 'En marche'), ('OFF', "À l'arrêt"), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10)),
                ('puissance_actuelle_kw', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energie_cumulee_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('statut_synchronisation', models.CharField(choices=[('UNKNOWN', 'Inconnu'), ('SYNCHRONIZED', 'Synchronisé'), ('OUT_OF_SYNC', 'Désynchronisé')], default='UNKNOWN', max_length=16)),
                ('date_etat_souhaite', models.DateTimeField(blank=True, null=True)),
                ('date_etat_rapporte', models.DateTimeField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('equipement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='energy_assets.equipement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('puissance_actuelle_kw__gte', 0)), name='etat_puissance_non_negative'), models.CheckConstraint(condition=models.Q(('energie_cumulee_kwh__gte', 0)), name='etat_energie_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ProfilFonctionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_fonctionnement', to='energy_assets.equipement')),
            ],
            options={
                'ordering': ('jour_semaine', 'heure_debut'),
                'constraints': [models.UniqueConstraint(fields=('equipement', 'jour_semaine', 'heure_debut'), name='profil_equip_jour_start_uq'), models.CheckConstraint(condition=models.Q(('heure_debut__lt', models.F('heure_fin'))), name='profil_heure_fin_apres_debut')],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('site', 'nom'), name='zone_site_nom_unique'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['site', 'monitoring_active'], name='equip_site_monitor_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipement',
            constraint=models.CheckConstraint(condition=models.Q(('puissance_nominale_kw__gte', 0)), name='equip_puissance_nom_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='equipement',
            constraint=models.CheckConstraint(condition=models.Q(('puissance_veille_kw__gte', 0)), name='equip_puissance_veille_non_neg'),
        ),
    ]
