# Generated by Django 5.2.17 on 2026-10-08 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureCapteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unite', models.CharField(blank=True, max_length=24)),
                ('date_mesure', models.DateTimeField()),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='energy_assets.capteur')),
            ],
            options={
                'ordering': ('-date_mesure',),
                'indexes': [models.Index(fields=['capteur', 'date_mesure'], name='mesure_capteur_date_idx')],
            },
        ),
    ]
