# Generated by Django 5.2.17 on 2026-10-08 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_assets', '0002_mesurecapteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeEquipement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ON', 'Mettre en marche'), ('OFF', 'Arrêter')], max_length=3)),
                ('statut', models.CharField(choices=[('PENDING', "En attente d'envoi"), ('SENT', 'Envoyée'), ('CONFIRMED', 'Confirmée'), ('FAILED', 'Échouée')], default='PENDING', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_finalisation', models.DateTimeField(blank=True, null=True)),
                ('detail_echec', models.TextField(blank=True)),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_equipements', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='energy_assets.equipement')),
            ],
            options={
                'ordering': ('-date_creation',),
                'indexes': [models.Index(fields=['equipement', 'statut', 'date_creation'], name='cmd_equip_status_date_idx'), models.Index(fields=['statut', 'date_creation'], name='cmd_status_date_idx')],
            },
        ),
    ]
