# Generated by Django 5.2.17 on 2026-10-09 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_livrable_organisation_memoire'),
        ('energy_assets', '0003_commandeequipement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionVirtuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etat_cible', models.CharField(choices=[('ON', 'En marche'), ('OFF', "À l'arrêt")], max_length=3)),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puissance_reference_kw', models.DecimalField(decimal_places=3, max_digits=14)),
                ('puissance_scenario_kw', models.DecimalField(decimal_places=3, max_digits=14)),
                ('variation_energie_kwh', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source_puissance_reference', models.CharField(choices=[('MESURE', 'Puissance mesurée'), ('NOMINALE', 'Puissance nominale estimée'), ('VEILLE', 'Puissance de veille estimée')], max_length=10)),
                ('date_simulation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_virtuelles', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_virtuelles', to='energy_assets.equipement')),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_virtuelles', to='analysis.recommandation')),
            ],
            options={
                'ordering': ('-date_simulation',),
                'indexes': [models.Index(fields=['recommandation', 'date_simulation'], name='action_virt_reco_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duree_heures__gt', 0), ('duree_heures__lte', 24)), name='action_virt_duree_1_24h')],
            },
        ),
    ]
