# Generated by Django 5.2.17 on 2026-09-13 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('impact_estime', models.DecimalField(decimal_places=6, max_digits=18)),
                ('economie_estimee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unite', models.CharField(max_length=30)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('EN_COURS', 'En cours'), ('DECIDEE', 'Décidée'), ('REJETEE', 'Rejetée'), ('TERMINEE', 'Terminée')], default='PROPOSEE', max_length=20)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatMetrique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_metrique', models.CharField(max_length=80)),
                ('version_metrique', models.CharField(max_length=20)),
                ('valeur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unite', models.CharField(max_length=30)),
                ('periode_debut', models.DateTimeField()),
                ('periode_fin', models.DateTimeField()),
                ('baseline_type', models.CharField(blank=True, max_length=50)),
                ('baseline_valeur', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('baseline_nombre_observations', models.PositiveIntegerField(default=0)),
                ('completude', models.DecimalField(decimal_places=4, max_digits=5)),
                ('statut_qualite', models.CharField(choices=[('FIABLE', 'Fiable'), ('ESTIME', 'Estimé'), ('INSUFFISANT', 'Insuffisant')], max_length=20)),
                ('confiance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sources', models.JSONField(default=list)),
                ('limites', models.JSONField(default=list)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-periode_fin',),
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', max_length=20)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_responsables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultat', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField()),
                ('decideur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_prises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=80)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('GENERE', 'Généré'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('url_fichier', models.URLField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('fiche_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='organizations.ficheprojet')),
            ],
        ),
    ]
