# Generated by Django 5.2.17 on 2026-09-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('energy', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='energy.objectif'),
        ),
        migrations.AddField(
            model_name='decision',
            name='recommandation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='analysis.recommandation'),
        ),
        migrations.AddField(
            model_name='action',
            name='recommandation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analysis.recommandation'),
        ),
        migrations.AddField(
            model_name='resultatmetrique',
            name='compteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_metriques', to='organizations.compteur'),
        ),
        migrations.AddField(
            model_name='resultatmetrique',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_metriques', to='organizations.organisation'),
        ),
        migrations.AddConstraint(
            model_name='resultatmetrique',
            constraint=models.UniqueConstraint(fields=('organisation', 'compteur', 'code_metrique', 'periode_debut', 'periode_fin', 'version_metrique'), name='resultat_metrique_unique_par_periode'),
        ),
    ]
