# Generated by Django 5.2.17 on 2026-09-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_opportunitefinancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='anomalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations', to='analysis.anomalie'),
        ),
    ]
