# Generated by Django 5.2.17 on 2026-09-14 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date_mesure_impact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='economie_realisee_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='taux_realisation_impact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('severite', models.CharField(choices=[('SURVEILLANCE', 'Surveillance'), ('ALERTE', 'Alerte'), ('INVESTIGATION_PRIORITAIRE', 'Investigation prioritaire')], max_length=30)),
                ('valeur_observee', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valeur_attendue', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ecart_pourcentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('DETECTED', 'Détectée'), ('NEEDS_CONTEXT', 'Contexte requis'), ('CONFIRMED', 'Confirmée'), ('DISMISSED', 'Écartée'), ('ACTION_CREATED', 'Action créée'), ('RESOLVED', 'Résolue')], default='DETECTED', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='organizations.organisation')),
                ('resultat_metrique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='analysis.resultatmetrique')),
            ],
            options={
                'ordering': ('-date_detection',),
            },
        ),
        migrations.CreateModel(
            name='DocumentEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('POLITIQUE', 'Politique interne'), ('RAPPORT', 'Rapport'), ('METHODOLOGIE', 'Méthodologie'), ('SUBVENTION', 'Dossier de subvention'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('contenu_texte', models.TextField()),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('indexe_rag', models.BooleanField(default=False)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('depose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_entreprise_deposes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_entreprise', to='organizations.organisation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_entreprise_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_depot',),
            },
        ),
        migrations.CreateModel(
            name='Hypothese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('preuves', models.JSONField(blank=True, default=list)),
                ('confiance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('CONFIRMEE', 'Confirmée'), ('REJETEE', 'Rejetée')], default='PROPOSEE', max_length=20)),
                ('genere_par_ia', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='analysis.anomalie')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='MemoireStrategique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=180)),
                ('signal_initial', models.TextField()),
                ('hypothese_texte', models.TextField(blank=True)),
                ('action_texte', models.TextField(blank=True)),
                ('impact_attendu_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('impact_mesure_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('taux_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('A_VERIFIER', 'À vérifier'), ('PARTIELLEMENT_CONFIRMEE', 'Partiellement confirmée'), ('CONFIRMEE', 'Confirmée')], default='A_VERIFIER', max_length=30)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('indexee_rag', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires', to='analysis.action')),
                ('anomalie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires', to='analysis.anomalie')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires_strategiques', to='organizations.organisation')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='ObservationOperationnelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('date_observation', models.DateTimeField()),
                ('creneau', models.CharField(blank=True, max_length=10)),
                ('valide', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_creees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='organizations.organisation')),
            ],
            options={
                'ordering': ('-date_observation',),
            },
        ),
    ]
