# Generated by Django 5.2.17 on 2026-09-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_action_date_mesure_impact_and_more'),
        ('energy', '0004_relevesolde'),
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatmetrique',
            name='fichier_source',
            field=models.ForeignKey(blank=True, help_text="Fichier source à l'origine de ce résultat, quand il provient d'un import OCR/capture plutôt que d'un calcul sur relevés.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_metriques', to='energy.fichiersource'),
        ),
        migrations.AddConstraint(
            model_name='resultatmetrique',
            constraint=models.UniqueConstraint(condition=models.Q(('fichier_source__isnull', False)), fields=('fichier_source',), name='resultat_metrique_unique_par_fichier_source'),
        ),
    ]
