# Generated by Django 5.2.17 on 2026-09-20 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_resultatmetrique_fichier_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportuniteFinancement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisme', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('taux_financement_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('criteres_eligibilite', models.TextField()),
                ('secteur', models.CharField(blank=True, max_length=150)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('url_source', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('A_VERIFIER', 'À vérifier'), ('EXPIRE', 'Expiré')], default='A_VERIFIER', max_length=20)),
                ('date_ingestion', models.DateTimeField(auto_now=True)),
                ('source_ingestion', models.CharField(default='n8n', max_length=50)),
            ],
            options={
                'ordering': ('date_limite',),
            },
        ),
    ]
