# Generated by Django 5.2.17 on 2026-09-19 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
        ('organizations', '0003_organisation_type_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeTarifaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(default='DOMESTIQUE_PETITE_PUISSANCE', max_length=50)),
                ('nom_tranche', models.CharField(max_length=80)),
                ('ordre', models.PositiveIntegerField()),
                ('kwh_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwh_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_fcfa_par_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_entree_vigueur', models.DateField()),
                ('date_fin_vigueur', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('categorie', 'ordre'),
            },
        ),
        migrations.CreateModel(
            name='AchatWoyofal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(unique=True)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kwh_credites', models.DecimalField(decimal_places=3, max_digits=10)),
                ('kwh_predits', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('date_achat', models.DateTimeField()),
                ('source', models.CharField(choices=[('SAISIE', 'Saisie'), ('SMS', 'SMS'), ('PHOTO', 'Photo')], default='SAISIE', max_length=10)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_woyofal', to='organizations.compteur')),
            ],
            options={
                'ordering': ('-date_achat',),
            },
        ),
    ]
