# Generated by Django 5.2.17 on 2026-09-20 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_seed_bareme_2026'),
        ('organizations', '0003_organisation_type_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveSolde',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(unique=True)),
                ('kwh_restants', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_releve', models.DateTimeField()),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_solde', to='organizations.compteur')),
            ],
            options={
                'ordering': ('-date_releve',),
            },
        ),
    ]
