# Generated by Django 5.2.17 on 2026-09-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_relevesolde'),
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdonnees',
            name='compteur',
            field=models.ForeignKey(blank=True, help_text='Compteur concerné par cet import, si connu — optionnel pour un import OCR classique sans sélection explicite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_donnees', to='organizations.compteur'),
        ),
    ]
