# Generated by Django 5.2.17 on 2026-09-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_importdonnees_compteur'),
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneeenergetique',
            name='creneau',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donneeenergetique',
            name='date_releve',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='donneeenergetique',
            constraint=models.UniqueConstraint(condition=models.Q(('creneau__gt', '')), fields=('compteur', 'date_releve', 'creneau'), name='donnee_energetique_compteur_date_creneau_unique'),
        ),
    ]
