# Generated by Django 5.2.17 on 2026-09-27 11:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_donneeenergetique_creneau_and_more'),
        ('organizations', '0005_organisation_details_demande'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSuiviEnergetique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('mode_mesure', models.CharField(choices=[('INDEX_CUMULATIF', 'Index cumulatif (SENELEC)'), ('SOLDE_WOYOFAL', 'Solde restant (Woyofal)')], max_length=24)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_suivi_energetique', to='organizations.compteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_suivi_energetique', to='organizations.site')),
            ],
            options={
                'ordering': ('site__nom', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='RechargeRituelWoyofal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=14)),
                ('kwh_credites', models.DecimalField(decimal_places=3, max_digits=12)),
                ('effectuee_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('point_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges_rituel', to='energy.pointsuivienergetique')),
            ],
            options={
                'ordering': ('-effectuee_le',),
            },
        ),
        migrations.CreateModel(
            name='ReleveRituelEnergetique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date_releve', models.DateField()),
                ('creneau', models.CharField(choices=[('08:00', '08:00 — Référence'), ('11:00', '11:00'), ('14:00', '14:00'), ('17:00', '17:00'), ('20:00', '20:00')], max_length=5)),
                ('valeur_kwh', models.DecimalField(decimal_places=6, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('observe_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('point_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_rituel', to='energy.pointsuivienergetique')),
            ],
            options={
                'ordering': ('-date_releve', 'creneau'),
            },
        ),
        migrations.AddConstraint(
            model_name='pointsuivienergetique',
            constraint=models.UniqueConstraint(fields=('site', 'nom'), name='point_suivi_site_nom_unique'),
        ),
        migrations.AddConstraint(
            model_name='rechargerituelwoyofal',
            constraint=models.CheckConstraint(condition=models.Q(('montant_fcfa__gt', 0)), name='recharge_rituel_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='rechargerituelwoyofal',
            constraint=models.CheckConstraint(condition=models.Q(('kwh_credites__gt', 0)), name='recharge_rituel_kwh_positifs'),
        ),
        migrations.AddConstraint(
            model_name='releverituelenergetique',
            constraint=models.UniqueConstraint(fields=('point_suivi', 'date_releve', 'creneau'), name='releve_rituel_point_date_creneau_unique'),
        ),
        migrations.AddConstraint(
            model_name='releverituelenergetique',
            constraint=models.CheckConstraint(condition=models.Q(('valeur_kwh__gte', 0)), name='releve_rituel_valeur_non_negative'),
        ),
    ]
