# Generated by Django 5.2.17 on 2026-09-25 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_compteur_puissance_souscrite_kva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('limites', models.JSONField(blank=True, default=dict)),
                ('fonctionnalites', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('TRIALING', 'Essai'), ('ACTIVE', 'Actif'), ('PAST_DUE', 'Paiement en retard'), ('GRACE_PERIOD', 'Période de grâce'), ('SUSPENDED', 'Suspendu'), ('CANCELED', 'Annulé'), ('EXPIRED', 'Expiré')], max_length=30)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=10)),
                ('debut', models.DateTimeField()),
                ('fin_periode', models.DateTimeField()),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('fin_acces_si_annule', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.CharField(choices=[('PAYDUNYA', 'PayDunya'), ('PAYTECH', 'PayTech'), ('FLUTTERWAVE', 'Flutterwave'), ('MANUAL', 'Manuel')], max_length=50)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='organizations.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
            ],
            options={
                'ordering': ('-debut',),
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('periode_debut', models.DateTimeField()),
                ('periode_fin', models.DateTimeField()),
                ('date_echeance', models.DateTimeField()),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouverte'), ('PAID', 'Payée'), ('PAST_DUE', 'En retard'), ('VOID', 'Annulée'), ('UNCOLLECTIBLE', 'Irrécouvrable')], default='DRAFT', max_length=30)),
                ('external_invoice_id', models.CharField(blank=True, max_length=255)),
                ('pdf_url', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='billing.abonnement')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='organizations.organisation')),
            ],
            options={
                'ordering': ('-periode_debut',),
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('methode', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('CANCELED', 'Annulé')], default='PENDING', max_length=30)),
                ('external_payment_id', models.CharField(max_length=255, unique=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='billing.facture')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='organizations.organisation')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAbonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(blank=True, max_length=30)),
                ('nouveau_statut', models.CharField(blank=True, max_length=30)),
                ('raison', models.CharField(max_length=100)),
                ('date_effet', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='billing.abonnement')),
                ('ancien_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
                ('nouveau_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.PositiveIntegerField()),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'Notification interne')], max_length=20)),
                ('planifiee_le', models.DateTimeField()),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', "En cours d'envoi"), ('SENT', 'Envoyée'), ('CANCELED', 'Annulée'), ('FAILED', 'Échouée')], default='PENDING', max_length=30)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='billing.facture')),
            ],
            options={
                'ordering': ('planifiee_le',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fournisseur', models.CharField(max_length=50)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('traite_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fournisseur', 'external_event_id'), name='webhook_event_unique_par_fournisseur')],
            },
        ),
    ]
