# Generated by Django 5.2.17 on 2026-09-27 16:20

from datetime import timedelta

from django.db import migrations, models


def initialiser_fin_periode_grace(apps, schema_editor):
    Abonnement = apps.get_model("billing", "Abonnement")
    for abonnement in Abonnement.objects.filter(statut="GRACE_PERIOD").iterator():
        abonnement.fin_grace = abonnement.fin_periode + timedelta(days=7)
        abonnement.save(update_fields=("fin_grace",))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='fin_grace',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(initialiser_fin_periode_grace, migrations.RunPython.noop),
    ]
