# Generated by Django 5.2.17 on 2026-09-13 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacteurEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type_energie', models.CharField(max_length=80)),
                ('valeur', models.DecimalField(decimal_places=6, max_digits=14)),
                ('unite', models.CharField(max_length=50)),
                ('source_reglementaire', models.CharField(max_length=180)),
                ('version', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=80)),
                ('valeur', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unite', models.CharField(max_length=30)),
                ('periode', models.DateTimeField()),
                ('methode_calcul', models.TextField()),
                ('date_calcul', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FichierSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='fichiers-sources/%Y/%m/%d/')),
                ('chemin_stockage', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(max_length=120)),
                ('taille_octets', models.PositiveBigIntegerField(default=0)),
                ('hash', models.CharField(max_length=128)),
                ('texte_brut_cache', models.TextField(blank=True, default='')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('depose_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichiers_sources_deposes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_sources', to='organizations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.DateTimeField()),
                ('consommation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emissions', models.DecimalField(decimal_places=6, max_digits=18)),
                ('economie', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unite', models.CharField(max_length=30)),
                ('fiche_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_performance', to='organizations.ficheprojet')),
            ],
            options={
                'ordering': ('-periode',),
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=80)),
                ('valeur_cible', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unite', models.CharField(max_length=30)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('progression_actuelle', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('prevision', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('ATTEINT', 'Atteint'), ('ABANDONNE', 'Abandonné')], default='BROUILLON', max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='organizations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurObjectif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('unite', models.CharField(max_length=30)),
                ('valeur_initiale', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valeur_cible', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valeur_actuelle', models.DecimalField(decimal_places=6, max_digits=18)),
                ('progression', models.DecimalField(decimal_places=2, max_digits=8)),
                ('indicateurs', models.ManyToManyField(blank=True, related_name='objectifs_associes', to='energy.indicateur')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs_objectifs', to='energy.objectif')),
            ],
        ),
        migrations.AddField(
            model_name='indicateur',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='energy.objectif'),
        ),
        migrations.CreateModel(
            name='SourceDonnee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=80)),
                ('origine', models.CharField(max_length=180)),
                ('frequence', models.CharField(max_length=80)),
                ('statut_synchronisation', models.CharField(max_length=50)),
                ('derniere_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_donnees', to='organizations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDonnees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('type_donnees', models.CharField(max_length=100)),
                ('nombre_lignes', models.PositiveIntegerField(default=0)),
                ('nombre_erreurs', models.PositiveIntegerField(default=0)),
                ('score_qualite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('HORS_PERIMETRE', 'Hors périmètre'), ('REVUE_REQUISE', 'Revue requise'), ('INCOHERENT', 'Incohérent'), ('TERMINE', 'Terminé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('ocr_statut', models.CharField(blank=True, default='', max_length=30)),
                ('ocr_erreur', models.TextField(blank=True, default='')),
                ('score_lisibilite', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('score_pertinence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('donnees_extraites', models.JSONField(blank=True, default=dict)),
                ('rapport_analyse', models.JSONField(blank=True, default=dict)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('fichier_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_donnees', to='energy.fichiersource')),
                ('lance_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports_lances', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports_donnees', to='organizations.organisation')),
                ('source_donnee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_donnees', to='energy.sourcedonnee')),
            ],
        ),
        migrations.CreateModel(
            name='DonneeEnergetique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unite', models.CharField(max_length=30)),
                ('periode_debut', models.DateTimeField()),
                ('periode_fin', models.DateTimeField()),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('source', models.CharField(max_length=150)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_energetiques', to='organizations.compteur')),
                ('facteur_emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donnees_converties', to='energy.facteuremission')),
                ('source_donnee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donnees_energetiques', to='energy.sourcedonnee')),
            ],
            options={
                'ordering': ('-periode_debut',),
            },
        ),
        migrations.CreateModel(
            name='SyntheseFinanciere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cout_energie', models.DecimalField(decimal_places=2, max_digits=18)),
                ('economie_estimee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('economie_realisee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('retour_investissement', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_calcul', models.DateTimeField()),
                ('fiche_projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synthese_financiere', to='organizations.ficheprojet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fichiersource',
            constraint=models.UniqueConstraint(fields=('hash', 'organisation'), name='fichier_source_hash_organisation_unique'),
        ),
    ]
