# Generated by Django 5.2.17 on 2026-09-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_pointsuivienergetique_rechargerituelwoyofal_and_more'),
        ('organizations', '0005_organisation_details_demande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointsuivienergetique',
            options={'ordering': ('organisation__nom', 'site__nom', 'nom')},
        ),
        migrations.AddField(
            model_name='pointsuivienergetique',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_suivi_energetique', to='organizations.organisation'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE energy_pointsuivienergetique
                SET organisation_id = (
                    SELECT organisation_id
                    FROM organizations_site
                    WHERE organizations_site.id = energy_pointsuivienergetique.site_id
                )
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pointsuivienergetique',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_suivi_energetique', to='organizations.organisation'),
        ),
        migrations.AlterField(
            model_name='pointsuivienergetique',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_suivi_energetique', to='organizations.site'),
        ),
        migrations.AddConstraint(
            model_name='pointsuivienergetique',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('organisation', 'nom'), name='point_suivi_org_sans_site_nom_unique'),
        ),
    ]
