# Generated by Django 5.2.17 on 2026-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_alter_pointsuivienergetique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releverituelenergetique',
            name='creneau',
            field=models.CharField(choices=[('08:00', '08:00 — Matin'), ('12:00', '12:00 — Midi'), ('16:00', '16:00 — Après-midi'), ('20:00', '20:00 — Soir')], max_length=5),
        ),
    ]
